namespace :units do
  task :convert => :environment do
    base_unit_entries = []

    un_ece_20_units = YAML.safe_load(ERB.new(File.read(File.expand_path('config/units-of-measure/un-ece-20.yml', Rails.root))).result)
    re = /^(?:([, 0-9]*)(?: x )!?)?([, 0-9⁰-⁹⁻¹²³]*)?(.*)?$/
    un_ece_20_units.each do |unit|
      fixed_conversion_factor = fix_conversion_factor(unit['ConversionFactor'])
      md = fixed_conversion_factor.match(re)
      multiplier = md[1]
      potency = md[2]
      base_unit = md[3]

      multiplier&.strip!
      potency&.strip!
      base_unit&.strip!

      if multiplier.blank? && (!potency.nil? && !/[⁰-⁹⁻¹²³]+/.match(potency))
        multiplier = potency
        potency = ''
      end

      multiplier&.gsub!(',', '.')
      multiplier&.gsub!(' ', '')
      multiplier = multiplier.blank? ? 1 : BigDecimal(multiplier)

      unit['conversion'] = {}
      unit['conversion']['unit'] = base_unit

      power_of_ten = potency.match(/^10 *?([⁰-⁹⁻¹²³]+)$/)&.[](1)
      power_of_ten = superscript_to_number(power_of_ten) unless power_of_ten.nil?

      base_unit_multiplier = multiplier
      base_unit_multiplier *= (10**power_of_ten) unless power_of_ten.nil?
      unit['conversion']['factor'] = base_unit_multiplier.to_s.to_f
      is_base_unit = !base_unit.blank? && potency.blank? && multiplier == 1

      base_unit_entries << unit if is_base_unit
    end

    # rubocop:disable Style/CombinableLoops
    un_ece_20_units.each do |unit|
      next if unit['conversion']['unit'].blank?

      base_units = base_unit_entries.select { |entry| entry['conversion']['unit'] == unit['conversion']['unit'] }
      unit['conversion']['base_units'] = base_units.pluck('CommonCode')
    end

    un_ece_20_units.each do |unit|
      unit['conversion'].delete('unit')
    end
    # rubocop:enable Style/CombinableLoops

    result = "# This file has been autogenerated by `rake units:convert`\n#{un_ece_20_units.to_yaml}"
    File.write(File.expand_path('config/units-of-measure/un-ece-20-remastered.yml', Rails.root), result)
  end
end

def superscript_hash
  {
    '⁻' => '-', '⁰' => '0', '¹' => '1', '²' => '2', '³' => '3', '⁴' => '4', '⁵' => '5', '⁶' => '6', '⁷' => '7', '⁸' => '8', '⁹' => '9'
  }
end

# I know this is stupid, but I couldn't find a default ruby/rails method for this and wouldn't be
# bothered to write a nicer unicode mapper for these few characters:
def superscript_to_number(str)
  str = str.chars.map { |c| superscript_hash[c] }.join

  BigDecimal(str) unless str == ''
end

def number_to_superscript(str)
  conversion_hash = superscript_hash.invert
  str.chars.map { |c| conversion_hash[c] }.join
end

def fix_conversion_factor(conversion_factor)
  # m2 -> m²:
  conversion_factor = conversion_factor.gsub(%r{(\s|^|/)m2(\s|$|/)}, '\1m²\2')

  # m3 -> m³
  conversion_factor = conversion_factor.gsub(%r{(\s|^|/)m3(\s|$|/)}, '\1m³\2')

  # 10-15 m³ -> 10⁻¹⁵ m³:
  conversion_factor.gsub(%r{(\s|^|/)10 ?(- ?[0-9]+)(\s|$|/)}) { Regexp.last_match[1] + "10" + number_to_superscript(Regexp.last_match[2]) + Regexp.last_match[3] }
end
